apiVersion: apps/v1
kind: Deployment
metadata:
  name: gphoto-flask-deployment
  namespace: gphoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gphoto-flask
  template:
    metadata:
      labels:
        app: gphoto-flask
    spec:
      containers:
        - name: gphoto-flask
          image: singularis314/gphoto:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: photos-volume
              mountPath: /app/static/pics/
      volumes:
        - name: photos-volume
          hostPath:
            path: /home/dante/gPhoto/flask/materials-flask-google-login/static/pics/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: gphoto-metal-ln
  namespace: gphoto
spec:
  ports:
  - port: 448
    targetPort: 5000
  selector:
    app: gphoto-flask
  type: LoadBalancer
